import daisyui from "daisyui";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      {
        "custom-happy": {
          "primary": "#FACC15",
          "primary-content": "#422006",
          "secondary": "#EAB308",
          "secondary-content": "#422006",
          "accent": "#EAB308",
          "accent-content": "#422006",
          "neutral": "#2a323c",
          "neutral-content": "#A6ADBB",
          "base-100": "#FEF08A", // Yellow-200 (Stronger Yellow)
          "base-200": "#FDE047",
          "base-300": "#FACC15",
          "base-content": "#422006",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
        },
        "custom-angry": {
          "primary": "#F87171",
          "primary-content": "#450A0A",
          "secondary": "#EF4444",
          "secondary-content": "#450A0A",
          "accent": "#EF4444",
          "accent-content": "#450A0A",
          "neutral": "#2a323c",
          "neutral-content": "#A6ADBB",
          "base-100": "#FECDD3", // Rose-200 (Stronger Red)
          "base-200": "#FDA4AF",
          "base-300": "#FB7185",
          "base-content": "#450A0A",
          "info": "#3abff8",
          "success": "#36d399",
          "warning": "#fbbd23",
          "error": "#f87272",
        },
      },

    ],
  },
};
